// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NLC.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NLC.Infrastructure.Migrations
{
    [DbContext(typeof(NlcDbContext))]
    partial class NlcDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NLC.Core.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<Guid[]>("AssignedWarehouseIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000001"),
                            AssignedWarehouseIds = new Guid[0],
                            CreatedAt = new DateTime(2026, 3, 28, 11, 2, 3, 340, DateTimeKind.Utc).AddTicks(8290),
                            Email = "admin@nlc.demo",
                            IsActive = true,
                            PasswordHash = "$2a$11$IICN4KSYyC3jYoX5ZQEWWOokSQSqXWzmjEMoGB7xM6mpmR8pLPuHu",
                            Role = "admin"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000002"),
                            AssignedWarehouseIds = new[] { new Guid("11111111-0000-0000-0000-000000000001"), new Guid("11111111-0000-0000-0000-000000000002") },
                            CreatedAt = new DateTime(2026, 3, 28, 11, 2, 3, 500, DateTimeKind.Utc).AddTicks(4760),
                            Email = "supervisor@nlc.demo",
                            IsActive = true,
                            PasswordHash = "$2a$11$v0tn8ztlUih2lSPtN9uwkuNXmPCZ97eQ6JQshuQr44dHflsRSm7je",
                            Role = "supervisor"
                        });
                });

            modelBuilder.Entity("NLC.Core.Entities.ClockEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ClockInTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ClockOutTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PhaseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RecordedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("WorkerId");

                    b.ToTable("ClockEvents");
                });

            modelBuilder.Entity("NLC.Core.Entities.DispatchNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DispatchStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DnNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("DispatchNotes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 14, 8, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Carrefour DSF Branch",
                            DispatchStatus = "TALLIED",
                            DnNumber = "DN-2025-0210",
                            JobId = new Guid("55555555-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 1, 14, 8, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Carrefour Deira City Centre",
                            DispatchStatus = "PENDING",
                            DnNumber = "DN-2025-0211",
                            JobId = new Guid("55555555-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("NLC.Core.Entities.DispatchSkuLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<int>("DispatchedQty")
                        .HasColumnType("integer");

                    b.Property<Guid>("DnId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderedQty")
                        .HasColumnType("integer");

                    b.Property<int>("PickedQty")
                        .HasColumnType("integer");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkuDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("VarianceApproved")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DnId");

                    b.ToTable("DispatchSkuLines");
                });

            modelBuilder.Entity("NLC.Core.Entities.ErpSyncLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadSummary")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SyncType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("ErpSyncLogs");
                });

            modelBuilder.Entity("NLC.Core.Entities.JobCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AsnNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContainerNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentPhase")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ErpSynced")
                        .HasColumnType("boolean");

                    b.Property<bool>("GrnGenerated")
                        .HasColumnType("boolean");

                    b.Property<string>("JobNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("JobTypeConfigId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("PhasesSnapshot")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReactivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReactivatedBy")
                        .HasColumnType("text");

                    b.Property<string>("ReactivationReason")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JobNumber")
                        .IsUnique();

                    b.HasIndex("JobTypeConfigId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("JobCards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000001"),
                            AsnNumber = "ASN-10482",
                            ContainerNumber = "TCKU3450671",
                            CreatedAt = new DateTime(2025, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("33333333-0000-0000-0000-000000000001"),
                            CurrentPhase = "Tally",
                            CustomerName = "Al Futtaim",
                            ErpSynced = false,
                            GrnGenerated = false,
                            JobNumber = "JC-2025-0841",
                            JobType = "INBOUND",
                            JobTypeConfigId = new Guid("22222222-0000-0000-0000-000000000001"),
                            PhasesSnapshot = new[] { "Offloading", "Tally", "Putaway", "VAS", "Complete" },
                            Priority = "HIGH",
                            ProgressPercent = 62,
                            Status = "IN_PROGRESS",
                            WarehouseId = new Guid("11111111-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000002"),
                            AsnNumber = "ASN-10481",
                            ContainerNumber = "MSCU7821033",
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("33333333-0000-0000-0000-000000000001"),
                            CurrentPhase = "Offloading",
                            CustomerName = "ENOC",
                            ErpSynced = false,
                            GrnGenerated = false,
                            JobNumber = "JC-2025-0840",
                            JobType = "INBOUND",
                            JobTypeConfigId = new Guid("22222222-0000-0000-0000-000000000001"),
                            PhasesSnapshot = new[] { "Offloading", "Tally", "Putaway", "VAS", "Complete" },
                            Priority = "NORMAL",
                            ProgressPercent = 0,
                            Status = "PLANNED",
                            WarehouseId = new Guid("11111111-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 1, 14, 7, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("33333333-0000-0000-0000-000000000001"),
                            CurrentPhase = "PDA Picking",
                            CustomerName = "Carrefour",
                            ErpSynced = false,
                            GrnGenerated = false,
                            JobNumber = "JC-2025-0839",
                            JobType = "OUTBOUND",
                            JobTypeConfigId = new Guid("22222222-0000-0000-0000-000000000002"),
                            OrderNumber = "ORD-58821",
                            PhasesSnapshot = new[] { "Order & Pick List", "PDA Picking", "Dispatch Tally", "Loading", "Complete" },
                            Priority = "HIGH",
                            ProgressPercent = 45,
                            Status = "IN_PROGRESS",
                            WarehouseId = new Guid("11111111-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000004"),
                            CompletedAt = new DateTime(2025, 1, 13, 18, 0, 0, 0, DateTimeKind.Utc),
                            ContainerNumber = "HLXU4412009",
                            CreatedAt = new DateTime(2025, 1, 13, 6, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("33333333-0000-0000-0000-000000000001"),
                            CurrentPhase = "Complete",
                            CustomerName = "Spinneys",
                            ErpSynced = true,
                            GrnGenerated = false,
                            JobNumber = "JC-2025-0838",
                            JobType = "OUTBOUND",
                            JobTypeConfigId = new Guid("22222222-0000-0000-0000-000000000002"),
                            OrderNumber = "ORD-58810",
                            PhasesSnapshot = new[] { "Order & Pick List", "PDA Picking", "Dispatch Tally", "Loading", "Complete" },
                            Priority = "NORMAL",
                            ProgressPercent = 100,
                            Status = "COMPLETED",
                            WarehouseId = new Guid("11111111-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000005"),
                            AsnNumber = "ASN-10479",
                            ContainerNumber = "CAIU8830021",
                            CreatedAt = new DateTime(2025, 1, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("33333333-0000-0000-0000-000000000001"),
                            CurrentPhase = "Putaway",
                            CustomerName = "Lulu Group",
                            ErpSynced = false,
                            GrnGenerated = false,
                            JobNumber = "JC-2025-0837",
                            JobType = "INBOUND",
                            JobTypeConfigId = new Guid("22222222-0000-0000-0000-000000000001"),
                            PhasesSnapshot = new[] { "Offloading", "Tally", "Putaway", "VAS", "Complete" },
                            Priority = "URGENT",
                            ProgressPercent = 78,
                            ReactivatedAt = new DateTime(2025, 1, 14, 10, 0, 0, 0, DateTimeKind.Utc),
                            ReactivatedBy = "supervisor@nlc.demo",
                            ReactivationReason = "Customer reported missing items after GRN",
                            Status = "REACTIVATED",
                            WarehouseId = new Guid("11111111-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000006"),
                            AsnNumber = "ASN-10478",
                            ContainerNumber = "CMAU6710034",
                            CreatedAt = new DateTime(2025, 1, 15, 7, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("33333333-0000-0000-0000-000000000001"),
                            CurrentPhase = "Offloading",
                            CustomerName = "IKEA UAE",
                            ErpSynced = false,
                            GrnGenerated = false,
                            JobNumber = "JC-2025-0836",
                            JobType = "INBOUND",
                            JobTypeConfigId = new Guid("22222222-0000-0000-0000-000000000001"),
                            PhasesSnapshot = new[] { "Offloading", "Tally", "Putaway", "VAS", "Complete" },
                            Priority = "NORMAL",
                            ProgressPercent = 15,
                            Status = "IN_PROGRESS",
                            WarehouseId = new Guid("11111111-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("NLC.Core.Entities.JobPhaseLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CompletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PhaseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhaseStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobPhaseLogs");
                });

            modelBuilder.Entity("NLC.Core.Entities.JobTypeConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErpPushPhase")
                        .HasColumnType("text");

                    b.Property<string>("GrnTriggerPhase")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.PrimitiveCollection<string[]>("Phases")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("VasOptional")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("JobTypeConfigs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000001"),
                            ErpPushPhase = "Putaway",
                            GrnTriggerPhase = "Putaway",
                            IsActive = true,
                            Name = "INBOUND",
                            Phases = new[] { "Offloading", "Tally", "Putaway", "VAS", "Complete" },
                            VasOptional = true
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000002"),
                            ErpPushPhase = "Loading",
                            IsActive = true,
                            Name = "OUTBOUND",
                            Phases = new[] { "Order & Pick List", "PDA Picking", "Dispatch Tally", "Loading", "Complete" },
                            VasOptional = false
                        });
                });

            modelBuilder.Entity("NLC.Core.Entities.PlanningSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AsnNumber")
                        .HasColumnType("text");

                    b.Property<string>("ContainerNumber")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<string>("DriverName")
                        .HasColumnType("text");

                    b.Property<string>("ErpReference")
                        .HasColumnType("text");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShipmentDescription")
                        .HasColumnType("text");

                    b.Property<DateOnly>("SlotDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("SlotTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("PlanningSlots");
                });

            modelBuilder.Entity("NLC.Core.Entities.SkuTallyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExpectedQty")
                        .HasColumnType("integer");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<int>("ScannedQty")
                        .HasColumnType("integer");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkuDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TallyStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TallyUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("TimeSpentMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("SkuTallyRecords");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44210e8d-4eef-4820-9397-9b0347069cd5"),
                            CompletedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedQty = 120,
                            JobId = new Guid("55555555-0000-0000-0000-000000000001"),
                            ScannedQty = 120,
                            SkuCode = "SKU-48821",
                            SkuDescription = "Carton Box 40x30",
                            Source = "ERP_SYNC",
                            TallyStatus = "COMPLETE",
                            TallyUserId = new Guid("44444444-0000-0000-0000-000000000003"),
                            TimeSpentMinutes = 18
                        },
                        new
                        {
                            Id = new Guid("bd52b5a5-a8e7-45f5-be55-f3069f3a21c5"),
                            CompletedAt = new DateTime(2025, 1, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            ExpectedQty = 50,
                            JobId = new Guid("55555555-0000-0000-0000-000000000001"),
                            ScannedQty = 50,
                            SkuCode = "SKU-48822",
                            SkuDescription = "Pallet Wrap Roll",
                            Source = "ERP_SYNC",
                            TallyStatus = "COMPLETE",
                            TallyUserId = new Guid("44444444-0000-0000-0000-000000000003"),
                            TimeSpentMinutes = 12
                        },
                        new
                        {
                            Id = new Guid("15d56a4c-56dc-46fc-b4fc-98bacc4eac58"),
                            ExpectedQty = 30,
                            JobId = new Guid("55555555-0000-0000-0000-000000000001"),
                            ScannedQty = 22,
                            SkuCode = "SKU-48823",
                            SkuDescription = "HDPE Drum 200L",
                            Source = "ERP_SYNC",
                            TallyStatus = "PARTIAL",
                            TallyUserId = new Guid("44444444-0000-0000-0000-000000000003"),
                            TimeSpentMinutes = 25
                        },
                        new
                        {
                            Id = new Guid("80bfa838-988b-47b4-9c93-3fe42b3727af"),
                            ExpectedQty = 200,
                            JobId = new Guid("55555555-0000-0000-0000-000000000001"),
                            ScannedQty = 0,
                            SkuCode = "SKU-48824",
                            SkuDescription = "Steel Bracket 2m",
                            Source = "ERP_SYNC",
                            TallyStatus = "PENDING",
                            TimeSpentMinutes = 0
                        });
                });

            modelBuilder.Entity("NLC.Core.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Location = "Jebel Ali, Dubai",
                            Name = "DXB-WH1"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Location = "Al Quoz, Dubai",
                            Name = "DXB-WH2"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Location = "Sharjah Industrial Area",
                            Name = "SHJ-WH1"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Location = "Mussafah, Abu Dhabi",
                            Name = "ABU-WH1"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Location = "Dubai Investments Park",
                            Name = "DXB-WH3"
                        });
                });

            modelBuilder.Entity("NLC.Core.Entities.Worker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<Guid[]>("AssignedWarehouseIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("ErpId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Skills")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("WorkerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000001"),
                            AssignedWarehouseIds = new[] { new Guid("11111111-0000-0000-0000-000000000001") },
                            ErpId = "EMP-001",
                            IsActive = true,
                            Name = "Rajan Pillai",
                            Skills = new[] { "Forklift" },
                            WorkerType = "PERMANENT"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000002"),
                            AssignedWarehouseIds = new[] { new Guid("11111111-0000-0000-0000-000000000001") },
                            ErpId = "EMP-002",
                            IsActive = true,
                            Name = "Sabu Thomas",
                            Skills = new[] { "Loading", "VAS" },
                            WorkerType = "PERMANENT"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000003"),
                            AssignedWarehouseIds = new[] { new Guid("11111111-0000-0000-0000-000000000001") },
                            ErpId = "EMP-003",
                            IsActive = true,
                            Name = "Ramesh Kumar",
                            Skills = new[] { "Tally" },
                            WorkerType = "PERMANENT"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000004"),
                            AssignedWarehouseIds = new[] { new Guid("11111111-0000-0000-0000-000000000001"), new Guid("11111111-0000-0000-0000-000000000002") },
                            ErpId = "EMP-004",
                            IsActive = true,
                            Name = "Jose Fernandez",
                            Skills = new[] { "Supervision" },
                            WorkerType = "PERMANENT"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000005"),
                            AssignedWarehouseIds = new[] { new Guid("11111111-0000-0000-0000-000000000002") },
                            ErpId = "EMP-005",
                            IsActive = true,
                            Name = "Arjun Nair",
                            Skills = new[] { "Loading", "PDA Picking" },
                            WorkerType = "CONTRACT"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000006"),
                            AssignedWarehouseIds = new[] { new Guid("11111111-0000-0000-0000-000000000002"), new Guid("11111111-0000-0000-0000-000000000005") },
                            ErpId = "EMP-006",
                            IsActive = true,
                            Name = "Priya Menon",
                            Skills = new[] { "Tally" },
                            WorkerType = "PERMANENT"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000007"),
                            AssignedWarehouseIds = new[] { new Guid("11111111-0000-0000-0000-000000000005") },
                            ErpId = "EMP-007",
                            IsActive = true,
                            Name = "Mohammed Al Rashid",
                            Skills = new[] { "Supervision" },
                            WorkerType = "PERMANENT"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000008"),
                            AssignedWarehouseIds = new[] { new Guid("11111111-0000-0000-0000-000000000001") },
                            ErpId = "WRK-001",
                            IsActive = true,
                            Name = "Worker-1",
                            Skills = new[] { "Loading" },
                            WorkerType = "AD_HOC"
                        });
                });

            modelBuilder.Entity("NLC.Core.Entities.ClockEvent", b =>
                {
                    b.HasOne("NLC.Core.Entities.JobCard", "JobCard")
                        .WithMany("ClockEvents")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NLC.Core.Entities.Worker", "Worker")
                        .WithMany("ClockEvents")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobCard");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("NLC.Core.Entities.DispatchNote", b =>
                {
                    b.HasOne("NLC.Core.Entities.JobCard", "JobCard")
                        .WithMany("DispatchNotes")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobCard");
                });

            modelBuilder.Entity("NLC.Core.Entities.DispatchSkuLine", b =>
                {
                    b.HasOne("NLC.Core.Entities.DispatchNote", "DispatchNote")
                        .WithMany("SkuLines")
                        .HasForeignKey("DnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DispatchNote");
                });

            modelBuilder.Entity("NLC.Core.Entities.ErpSyncLog", b =>
                {
                    b.HasOne("NLC.Core.Entities.JobCard", "JobCard")
                        .WithMany("ErpSyncLogs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobCard");
                });

            modelBuilder.Entity("NLC.Core.Entities.JobCard", b =>
                {
                    b.HasOne("NLC.Core.Entities.JobTypeConfig", "JobTypeConfig")
                        .WithMany("JobCards")
                        .HasForeignKey("JobTypeConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NLC.Core.Entities.Warehouse", "Warehouse")
                        .WithMany("JobCards")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobTypeConfig");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("NLC.Core.Entities.JobPhaseLog", b =>
                {
                    b.HasOne("NLC.Core.Entities.JobCard", "JobCard")
                        .WithMany("PhaseLogs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobCard");
                });

            modelBuilder.Entity("NLC.Core.Entities.PlanningSlot", b =>
                {
                    b.HasOne("NLC.Core.Entities.Warehouse", "Warehouse")
                        .WithMany("PlanningSlots")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("NLC.Core.Entities.SkuTallyRecord", b =>
                {
                    b.HasOne("NLC.Core.Entities.JobCard", "JobCard")
                        .WithMany("SkuTallies")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobCard");
                });

            modelBuilder.Entity("NLC.Core.Entities.DispatchNote", b =>
                {
                    b.Navigation("SkuLines");
                });

            modelBuilder.Entity("NLC.Core.Entities.JobCard", b =>
                {
                    b.Navigation("ClockEvents");

                    b.Navigation("DispatchNotes");

                    b.Navigation("ErpSyncLogs");

                    b.Navigation("PhaseLogs");

                    b.Navigation("SkuTallies");
                });

            modelBuilder.Entity("NLC.Core.Entities.JobTypeConfig", b =>
                {
                    b.Navigation("JobCards");
                });

            modelBuilder.Entity("NLC.Core.Entities.Warehouse", b =>
                {
                    b.Navigation("JobCards");

                    b.Navigation("PlanningSlots");
                });

            modelBuilder.Entity("NLC.Core.Entities.Worker", b =>
                {
                    b.Navigation("ClockEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
